# Generated by Django 5.2.2 on 2025-06-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='description',
        ),
    ]
