# Generated by Django 5.2.2 on 2025-06-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0002_remove_mediaitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaitem',
            old_name='title',
            new_name='search_field',
        ),
    ]
