# Generated by Django 5.2.3 on 2025-07-02 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0003_rename_title_mediaitem_search_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='search_field',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
