# Generated by Django 5.2.3 on 2025-07-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0004_remove_mediaitem_search_field_mediaitem_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='poster_url',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0OCD8vwRqyldCWESsUQ9_r2YQzHMPHXi1MQ&s'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tmdb_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
