# Generated by Django 5.2.3 on 2025-07-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0005_mediaitem_poster_url_mediaitem_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
