# Generated by Django 5.2.3 on 2025-07-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0006_alter_mediaitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
