# Generated by Django 5.2.3 on 2025-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0007_alter_mediaitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
