# Generated by Django 5.2.3 on 2025-07-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0008_mediaitem_genre_mediaitem_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='type',
            field=models.CharField(default='films'),
        ),
    ]
