# Generated by Django 5.2.3 on 2025-07-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0010_alter_mediaitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.SlugField(),
        ),
    ]
