# Generated by Django 5.2.3 on 2025-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_menu', '0011_alter_mediaitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
